### ISSUE TITLE
portCONFIGURE_TIMER_FOR_RUN_TIME_STATS implementation missing

### ISSUE THREAD

**Issue by zhaomh1998** [discord-intech/FreeRTOS-Teensy4#3] opened 2020-02-27 12:05 UTC
Dear Julian,

Thanks for the awesome work! I'm relatively new to FreeRTOS so hopefully I'm not making some stupid mistake here.

I'm trying to get vTaskGetRunTimeStats to work, and as I read from the [documentation](https://www.freertos.org/rtos-run-time-stats.html) under the "Configuration and Usage", it seems like I need to define three macros to enable this feature.

- The first one `configGENERATE_RUN_TIME_STATS` is in FreeRTOSConfig, and I changed it to 1
```c
#define configGENERATE_RUN_TIME_STATS 0
```

- The second one `portCONFIGURE_TIMER_FOR_RUN_TIME_STATS()`I found the definition in [Line 710 of src/FreeRTOS.h](https://github.com/discord-intech/FreeRTOS-Teensy4/blob/master/src/FreeRTOS.h#L710). However I did not see any implementation to it. If I leave as is and compile, this message will show up: 

> <Library Path>/src/FreeRTOS.h:698:4: error: #error If configGENERATE_RUN_TIME_STATS is defined then portCONFIGURE_TIMER_FOR_RUN_TIME_STATS must also be defined. portCONFIGURE_TIMER_FOR_RUN_TIME_STATS should call a port layer function to setup a peripheral timer/counter that can then be used as the run time counter time base.

As the documentation says: 
> It is intended that the application designer uses the macro to configure a suitable time base. Some examples are provided below.

I'm suspecting there is some implementation on this missing if I'm right. The documentation provided some examples of the implementation but they are not for Teensy and I have no idea how this works.

## System Information
- Library version 10.0.4
- Tried both on Arduino IDE 1.8.7 and pio 4.2.1
## Code to reproduce
The code tries to use `vTaskGetRunTimeStats`. It will produce a linker error `undefined reference to `vTaskGetRunTimeStats'` if left the FreeRTOS.h at default (`#define configGENERATE_RUN_TIME_STATS 0`)

Once change that to 1, the issue I'm having will show up.
```c
// Modified from https://github.com/discord-intech/FreeRTOS-Teensy4/blob/master/examples/blink_task.cpp

#include <FreeRTOS_TEENSY4.h>

static void Thread1(void* arg) {
  char buf[200];
  while (1) {
    Serial.println("Hello!");
    vTaskGetRunTimeStats(buf);
    vTaskDelay((200L * configTICK_RATE_HZ) / 1000L);
  }
}

void setup() {
  portBASE_TYPE s1;

  Serial.begin(9600);

  // create task at priority two
  s1 = xTaskCreate(Thread1, NULL, configMINIMAL_STACK_SIZE, NULL, 2, NULL);

  // check for creation errors
  if (s1 != pdPASS) {
    Serial.println("Creation problem");
    while (1);
  }

  Serial.println("Starting the scheduler !");

  // start scheduler
  vTaskStartScheduler();
  Serial.println("Insufficient RAM");
  while (1);
}
//------------------------------------------------------------------------------
// WARNING idle loop has a very small stack (configMINIMAL_STACK_SIZE)
// loop must never block
void loop() {
  // Not used.
}
```

Thanks a lot,
Scott

**Comment by juliandesvignes** [comment] 2020-02-28 04:02
Hi Scott,

First of all, thank you for your very well detailed issue.

I am completely aware of the lack of setup for the run-time stats, mostly due to a dilemma. 
As you may know, this involves setting up another timer that will be at least 10x faster than the tick-rate. The problem is that the only available timers I have are already used for the PWM in Teensyduino. This is normally a non-issue for power-users, as they know the impact of using this feature of FreeRTOS, but Teensyduino is based on Arduino which is focused on abstracting all the gritty work with the MCU. Casual users of Teensy devices may not want to have to deal with Timers. For that reason, I did not implement this feature, as of now.

Since I realized that people using this stats feature are usually power users, I decided to implement it anyway, but it does not affect the PWM timer if it is deactivated.

I made and tested a quick implementation in the `runtime_stats` branch, please test it and see if it work for you too. I do not have your FreeRTOS configuration file, but do not forget that you also have to set `configUSE_STATS_FORMATTING_FUNCTIONS` to something >0 in addition to `configGENERATE_RUN_TIME_STATS`.

Best,
Julian

**Comment by zhaomh1998** [comment] 2020-02-28 09:40
Dear Julian,

Thanks for the fast response! I cloned the `runtime_stats` branch and after testing, it works besides a small issue:

It would compile and work fine under Arduino IDE with a single sketch. However, I'm getting `multiple definition of 'ulTimerCounter'` linker error in my pio project with multiple source files trying to
```c
#include <FreeRTOS_TEENSY4.h>
```

I suspect it's because in [line 18 of `src/FreeRTOSConfig.h`](https://github.com/discord-intech/FreeRTOS-Teensy4/pull/4/commits/6e812cf845d1ff21284f186639c8e94b593c9f8a#diff-01a29baeb1d5d389ad38546f9953cdf5R18) you declared: 
```c
volatile uint64_t ulTimerCounter;
```
and this declaration was copied multiple times during compiling.

I see you put extern this variable in [line 196 of `src/port.c`](https://github.com/discord-intech/FreeRTOS-Teensy4/pull/4/commits/6e812cf845d1ff21284f186639c8e94b593c9f8a#diff-9040643e0656f2a0330f5b2bf95a4f60R196). Did you mean the other way? (Put extern in the header and actual declaration here)?
```c
extern volatile uint64_t ulTimerCounter;
```

After I added `extern` into [line 18 of `src/FreeRTOSConfig.h`](https://github.com/discord-intech/FreeRTOS-Teensy4/pull/4/commits/6e812cf845d1ff21284f186639c8e94b593c9f8a#diff-01a29baeb1d5d389ad38546f9953cdf5R18) and removed the `extern` in [line 196 of `src/port.c`](https://github.com/discord-intech/FreeRTOS-Teensy4/pull/4/commits/6e812cf845d1ff21284f186639c8e94b593c9f8a#diff-9040643e0656f2a0330f5b2bf95a4f60R196) everything works perfectly.

I had this kind of `multiple definition` issues a lot and usually it's because I declared something in a header file that got included in multiple source code files. Most of the time adding `extern` before that declaration and put the declaration into a source code file works for me. I'm not very experienced in C so this issue could totally be how I structured my code is wrong.

Again, thanks for the great work and fast response. Have a great day!

Regards,
Scott

**Comment by juliandesvignes** [comment] 2020-03-02 07:19
Dear Scott,

Good catch ! Thanks for that !
I should have re-read my code before committing, sorry.
If it works for you, I'll merge the branch and close this issue.

Best regards,
Julian

**Comment by zhaomh1998** [comment] 2020-03-02 08:46
Dear Julian,

Yes it works well. You can go ahead and merge the branch which closes the issue.

Have a great day,
Scott

**Closed as completed** 2020-03-02 23:01 UTC
